### ISSUE TITLE
Failed deployment

### ISSUE THREAD

**Issue by dipteshbosedxc** [Azure-Samples/serverless-chat-langchainjs#103]
Failed deployment

> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)

```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

> All the steps completed successfully, but still failed

### Any log messages given by the failure

>
![image](https://github.com/user-attachments/assets/63020ece-689b-44b6-88ca-05a5c00a5037)

### Expected/desired behavior

>

### OS and Version?

> Windows 11

### Versions

> Windows 11

### Mention any other details that might be useful

> ---
>
> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment]
Looking at the error message, it seems that Powershell isn't installed or accessible from the current context (see https://github.com/Azure-Samples/serverless-chat-langchainjs?tab=readme-ov-file#use-your-local-environment for install links).
Does it work if you try to run `pwsh` from the same terminal you ran the `azd up` command?

**Comment by dipteshbosedxc** [comment]
> Looking at the error message, it seems that Powershell isn't installed or accessible from the current context (see https://github.com/Azure-Samples/serverless-chat-langchainjs?tab=readme-ov-file#use-your-local-environment for install links). Does it work if you try to run `pwsh` from the same terminal you ran the `azd up` command?

No, it did not work. I had to install PWSH and clean up the resource group and purge the Cognitive Service soft delete before doing it again...
