### ISSUE TITLE
info2.txt is missing

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/serverless-chat-langchainjs#55]
> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)

```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>
1. azd up
2. use chat
3. select how to search and book rentals
4. Wait for answer and suggestions
5. from suggestions, select how can I cancel a rental booking
6. from answer, select citiation for info2.txt
7. `{"error":"Document not found"}`

### Any log messages given by the failure

>

### Expected/desired behavior

> Citation goes to text.

### OS and Version?

> Windows 11

### Versions

> 

### Mention any other details that might be useful

<img width="728" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/3275fb49-93d9-41c2-9dad-7e9b71747394">

<img width="609" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/41597107/6e164081-6530-404e-8d06-667888a38d00">

> ---
>
> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment]
This document doesn't exists, this is an error from the generated models.
I'm currently investigating why the GPT3.5 seems to perform worse than what it used to do, error like these were almost non-existant. Maybe default parameters in Langchain have been updated.

**Comment by sinedied** [comment]
The prompt was updated, and model was upgraded to gpt-4-turbo. I've yet to see this error again for now on the deployed version, so I'm closing this one for now.
