### ISSUE TITLE
Upload pdf by API

### ISSUE THREAD

**Issue by davidfungf** [Azure-Samples/serverless-chat-langchainjs#63]
I want to upload a pdf file by the API (POST  `https://x.x.x.x/api/documents/`) using the following curl command. But it returned 401 unauthorized.

`curl --location 'https://xxx.app.github.dev/api/documents/' \
--header 'Content-Type: multipart/form-data' \
--form '=@"/C:/Users/R008128.pdf"'`

### This issue is for a: (mark with an `x`)

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

> 401 Unauthorized

### Expected/desired behavior

>

### OS and Version? 

> Azure cloud

### Mention any other details that might be useful

> ---
>
> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment]
From you URL I understand that you're trying to send the file to the server running locally in your Codespaces?

First, can you try running the curl command locally in your Codespaces terminal, using a format like this:
```
curl -X POST -F "file=@R008128.pdf" http://localhost:7071/api/documents
```
Note that you have to set the `file` key otherwise it won't work

**Comment by sinedied** [comment]
Good to hear 🙂
