### ISSUE TITLE
Embedding model change

### ISSUE THREAD

**Issue by davidfungf** [Azure-Samples/serverless-chat-langchainjs#69]
According to the [article](https://openai.com/index/new-embedding-models-and-api-updates/), If I want to change the embedding model from `text-embedding-ada-002` to` text-embedding-3-small`. Which code shall I modify?

Your tutorial inspires my interests on RAG very much. Thank you!!

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by davidfungf** [comment]
I just found it in the faq.md. 

`azd env set AZURE_OPENAI_API_EMBEDDINGS_MODEL text-embedding-3-large`

**Comment by glaucia86** [comment]
Hi, @davidfungf . How are you?

It depends. If you want to use the Azure OpenAI Service, you can use AI Studio to create the embedding you want to use and change it with the command used.

Now, if you're using an LLM's Open Source you should change the file contanst.ts

**Comment by sinedied** [comment]
Regarding the deployment, if changing the embedding model for the deployed version you need to delete the existing index in your AI Search instance in the portal:

<img width="1140" alt="image" src="https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/593151/a2abeb39-db11-4ffd-ad64-b85885708f93">

This is needed as the vector length might differ.

Then you need to redeploy the app with `azd up`

**Comment by davidfungf** [comment]
Thank you for your support! 

Suggestion: You may consider using [Azure Document Intelligence Layout Model](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/analyze-complex-documents-with-azure-document-intelligence/ba-p/4080770) to generate the Markdown components to enhance the data accuracy. I looking forward to seeing your post soon.

**Comment by sinedied** [comment]
Using Azure Document Intelligence is on our watchlist for a possible add-on, the initial idea for this one sample was to make it as simple as possible to understand.

We also have other more full-featured samples like [this one](https://github.com/Azure-Samples/azure-search-openai-demo), that uses Azure Document Intelligence for ingestion.
