### ISSUE TITLE
Export-ModuleMember error

### ISSUE THREAD

**Issue by kjohnsen-dk** [Azure-Samples/serverless-chat-langchainjs#79]
> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)

```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
```
azd auth login
azd up
```

>

### Any log messages given by the failure
![error](https://github.com/Azure-Samples/serverless-chat-langchainjs/assets/52370291/a3bae519-0c6c-4387-9fba-bb50b220e6ca)

>

### Expected/desired behavior
Expected to get a web service deployed.
>

### OS and Version?

> Windows 10

### Versions

>

### Mention any other details that might be useful

> ---
>
> Thanks! We'll be in touch soon.

**Comment by sinedied** [comment]
Thanks for your report!

Could you share more information about your current environment to help pinpoint the issue?
- Powershell version (open powershell and run `$PSVersionTable`):
- Are you using WSL? If yes, which distribution are you using? (`lsb_release -a`):
- Node.js version (`node -v`):
- NPM version (`npm -v`):

I think this error usually occurs when using older Powershell version, could you try update to Powershell 7 and try running `azp up` again?

**Comment by NanaXiong00** [comment]
@sinedied I also encountered the current problem on Windows, please help to fix it. The versions are as follows:
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows desktop.
- PowerShell: 7.4.4
- node: v20.12.2
- npm: 10.5.0

CC: @jongio

**Comment by sinedied** [comment]
@NanaXiong00 Thanks for the feedback. Could you try if this fix works for you? https://github.com/Azure-Samples/serverless-chat-langchainjs/pull/93

It seems like latest AZD versions now properly export env vars in hooks, so workaround aren't needed anymore.
