### ISSUE TITLE
Fail to run `azd up` command

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/serverless-chat-langchainjs#92]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/azure-samples/serverless-chat-langchainjs#deploy-the-sample), the error is as follows:
![image](https://github.com/user-attachments/assets/cc852271-5f62-4a5a-8543-314c37302c1f)

**Repro Steps:**
1. Open in GitHub Codespaces.
2. Run `azd auth login` 
3. Run `azd up`

**Environment:**
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespaces, Dev Containers and Windows desktop.

**Expected behavior:**
Run `azd up` can successfully.

@jongio and @sinedied for notification.

**Comment by sinedied** [comment]
Thanks for the report! Should be fixed now
